from sfa.infrastructure.models.enums import Position

# Mapeo base: API-Football position string → Position enum
BASE_POSITION_MAP: dict[str, Position] = {
    "Attacker":   Position.DEL,
    "Forward":    Position.DEL,   # API-Football usa "Forward", no "Attacker"
    "Midfielder": Position.MC,
    "Defender":   Position.DC,
    "Goalkeeper": Position.GK,
}

# Jugadores con posición refinada que API-Football no distingue correctamente.
# "Forward" genérico no diferencia DEL (9) de EXT (11/7).
# "Midfielder" no diferencia MC (8) de LAT (2/3) en algunos casos.
KNOWN_POSITIONS: dict[str, Position] = {
    # ── La Liga — Delanteros ────────────────────────────────────────────────
    "Kylian Mbappé":           Position.DEL,
    "Robert Lewandowski":      Position.DEL,
    "Julián Álvarez":          Position.DEL,
    "Alexander Sørloth":       Position.DEL,
    "Ayoze Pérez":             Position.DEL,
    "Ante Budimir":            Position.DEL,
    "Borja Iglesias":          Position.DEL,
    "En-Nesyri":               Position.DEL,
    "Gorka Guruzeta":          Position.DEL,
    "Hugo Duro":               Position.DEL,
    "Vitor Roque":             Position.DEL,
    # La Liga — Extremos
    "Raphinha":                Position.EXT,
    "Lamine Yamal":            Position.EXT,
    "Dani Olmo":               Position.EXT,
    "Vinícius Júnior":         Position.EXT,
    "Rodrygo":                 Position.EXT,
    "Nico Williams":           Position.EXT,
    "Ferran Torres":           Position.EXT,
    "Ansu Fati":               Position.EXT,
    "Bernardo Silva":          Position.EXT,
    "Brahim Díaz":             Position.EXT,
    "Dani Ceballos":           Position.EXT,
    "Mikel Oyarzabal":         Position.EXT,
    "Iñaki Williams":          Position.EXT,
    "Álex Berenguer":          Position.EXT,
    "Arda Güler":              Position.EXT,
    "Giuliano Simeone":        Position.EXT,
    "Ángel Correa":            Position.EXT,
    "Fermín López":            Position.EXT,
    "Takumi Minamino":         Position.EXT,
    # La Liga — Laterales
    "Alejandro Balde":         Position.LAT,
    "Jules Koundé":            Position.LAT,
    "Dani Carvajal":           Position.LAT,
    "Lucas Vázquez":           Position.LAT,
    "Ferland Mendy":           Position.LAT,
    "Fran García":             Position.LAT,
    "Jesús Navas":             Position.LAT,
    "Marcos Llorente":         Position.LAT,

    # ── Premier League — Delanteros ─────────────────────────────────────────
    "Harry Kane":              Position.DEL,
    "Erling Haaland":          Position.DEL,
    "Alexander Isak":          Position.DEL,
    "Ollie Watkins":           Position.DEL,
    "Darwin Núñez":            Position.DEL,
    "Gabriel Jesus":           Position.DEL,
    "Dominic Solanke":         Position.DEL,
    "Callum Wilson":           Position.DEL,
    "Ivan Toney":              Position.DEL,
    "Nicolas Jackson":         Position.DEL,
    "Jhon Durán":              Position.DEL,
    "Rodrigo Muniz":           Position.DEL,
    "Diogo Jota":              Position.DEL,
    "Matheus Cunha":           Position.DEL,
    "Raúl Jiménez":            Position.DEL,
    "Kai Havertz":             Position.DEL,
    "Evanilson":               Position.DEL,
    "Tammy Abraham":           Position.DEL,
    # Premier League — Extremos
    "Mohamed Salah":           Position.EXT,
    "Bukayo Saka":             Position.EXT,
    "Marcus Rashford":         Position.EXT,
    "Gabriel Martinelli":      Position.EXT,
    "Phil Foden":              Position.EXT,
    "Jack Grealish":           Position.EXT,
    "Jarrod Bowen":            Position.EXT,
    "Omar Marmoush":           Position.EXT,
    "Luis Díaz":               Position.EXT,
    "Cody Gakpo":              Position.EXT,
    "Son Heung-min":           Position.EXT,
    "Dejan Kulusevski":        Position.EXT,
    "Leandro Trossard":        Position.EXT,
    "Morgan Rogers":           Position.EXT,
    "Harvey Barnes":           Position.EXT,
    "Jacob Murphy":            Position.EXT,
    "Anthony Gordon":          Position.EXT,
    "Noni Madueke":            Position.EXT,
    "Eberechi Eze":            Position.EXT,
    "Jérémy Doku":             Position.EXT,
    "Ethan Nwaneri":           Position.EXT,
    "Ismaïla Sarr":            Position.EXT,
    "Savinho":                 Position.EXT,
    "Antony":                  Position.EXT,
    "Abdallah Sima":           Position.EXT,
    # Premier League — Laterales
    "Trent Alexander-Arnold":  Position.LAT,
    "Reece James":             Position.LAT,
    "Kyle Walker":             Position.LAT,
    "Andrew Robertson":        Position.LAT,
    "Joško Gvardiol":          Position.LAT,
    "Pedro Porro":             Position.LAT,
    "Ben White":               Position.LAT,
    "Marc Cucurella":          Position.LAT,
    "Raphaël Guerreiro":       Position.LAT,

    # ── Bundesliga — Delanteros ─────────────────────────────────────────────
    "Serhou Guirassy":         Position.DEL,
    "Victor Okoh Boniface":    Position.DEL,
    "Niclas Füllkrug":         Position.DEL,
    "Luca Waldschmidt":        Position.DEL,
    "Hugo Ekitiké":            Position.DEL,
    "Wout Weghorst":           Position.DEL,
    "Patrik Schick":           Position.DEL,
    "Jonathan Burkardt":       Position.DEL,
    "Loïs Openda":             Position.DEL,
    "Maximilian Beier":        Position.DEL,
    "Benjamin Šeško":          Position.DEL,
    "Tim Kleindienst":         Position.DEL,
    # Bundesliga — Extremos
    "Jamal Musiala":           Position.EXT,
    "Florian Wirtz":           Position.EXT,
    "Kingsley Coman":          Position.EXT,
    "Leroy Sané":              Position.EXT,
    "Michael Olise":           Position.EXT,
    "Serge Gnabry":            Position.EXT,
    "Karim Adeyemi":           Position.EXT,
    "Donyell Malen":           Position.EXT,
    "Jamie Gittens":           Position.EXT,
    "Ritsu Doan":              Position.EXT,
    "Thomas Müller":           Position.EXT,
    "Julian Brandt":           Position.EXT,
    "Felix Nmecha":            Position.EXT,
    "Vincenzo Grifo":          Position.EXT,
    # Bundesliga — Laterales
    "Alejandro Grimaldo":      Position.LAT,
    "Alphonso Davies":         Position.LAT,
    "Julian Ryerson":          Position.LAT,
    "Noussair Mazraoui":       Position.LAT,
    "Jeremie Frimpong":        Position.LAT,
    "Lukas Kübler":            Position.LAT,

    # ── Serie A — Delanteros ────────────────────────────────────────────────
    "Lautaro Martínez":        Position.DEL,
    "Dušan Vlahović":          Position.DEL,
    "Moise Kean":              Position.DEL,
    "Mateo Retegui":           Position.DEL,
    "Marcus Thuram":           Position.DEL,
    "Romelu Lukaku":           Position.DEL,
    "Arkadiusz Milik":         Position.DEL,
    "Gianluca Scamacca":       Position.DEL,
    "Artem Dovbyk":            Position.DEL,
    "Giacomo Raspadori":       Position.DEL,
    "Albert Guðmundsson":      Position.DEL,
    "Lorenzo Lucca":           Position.DEL,
    "Lucas Beltrán":           Position.DEL,
    "Eldor Shomurodov":        Position.DEL,
    "Santiago Giménez":        Position.DEL,
    "Vangelis Pavlidis":       Position.DEL,
    # Serie A — Extremos
    "Rafael Leão":             Position.EXT,
    "Ademola Lookman":         Position.EXT,
    "Christian Pulisic":       Position.EXT,
    "Khvicha Kvaratskhelia":   Position.EXT,
    "Federico Chiesa":         Position.EXT,
    "Kenan Yıldız":            Position.EXT,
    "Francisco Conceição":     Position.EXT,
    "Charles De Ketelaere":    Position.EXT,
    "Timothy Weah":            Position.EXT,
    "Paulo Dybala":            Position.EXT,
    "Matías Soulé":            Position.EXT,
    "Alexis Saelemaekers":     Position.EXT,
    "Nicolás González":        Position.EXT,
    "Daniel Maldini":          Position.EXT,
    "Samuel Lino":             Position.EXT,
    "Riccardo Orsolini":       Position.EXT,
    # Serie A — Laterales
    "Theo Hernández":          Position.LAT,
    "Federico Dimarco":        Position.LAT,
    "Denzel Dumfries":         Position.LAT,
    "Giovanni Di Lorenzo":     Position.LAT,
    "Davide Zappacosta":       Position.LAT,
    "Raoul Bellanova":         Position.LAT,
    "Rasmus Kristensen":       Position.LAT,
    "Robin Gosens":            Position.LAT,

    # ── Ligue 1 — Delanteros ────────────────────────────────────────────────
    "Jonathan David":          Position.DEL,
    "Gonçalo Ramos":           Position.DEL,
    "Mason Greenwood":         Position.DEL,
    "Randal Kolo Muani":       Position.DEL,
    "Evann Guessand":          Position.DEL,
    "Folarin Balogun":         Position.DEL,
    "Alexandre Lacazette":     Position.DEL,
    "Gaëtan Laborde":          Position.DEL,
    "Thierno Barry":           Position.DEL,
    "Arnaud Kalimuendo":       Position.DEL,
    "Thijs Dallinga":          Position.DEL,
    "Matthis Abline":          Position.DEL,
    "Emanuel Emegha":          Position.DEL,
    "Esteban Lepaul":          Position.DEL,
    "Lucas Stassin":           Position.DEL,
    "George Ilenikhena":       Position.DEL,
    "Mika Biereth":            Position.DEL,
    "Breel Embolo":            Position.DEL,
    # Ligue 1 — Extremos
    "Ousmane Dembélé":         Position.EXT,
    "Bradley Barcola":         Position.EXT,
    "Désiré Doué":             Position.EXT,
    "Rayan Cherki":            Position.EXT,
    "Maghnes Akliouche":       Position.EXT,
    "Amine Gouiri":            Position.EXT,
    "Edon Zhegrova":           Position.EXT,
    "Vanderson":               Position.EXT,
    "Marco Asensio":           Position.EXT,
    "Eliesse Ben Seghir":      Position.EXT,
    "Hakon Arnar Haraldsson":  Position.EXT,
    "Sofiane Diop":            Position.EXT,
    "Malick Fofana":           Position.EXT,
    "Senny Mayulu":            Position.EXT,
    "Osame Sahraoui":          Position.EXT,
    "Keito Nakamura":          Position.EXT,
    # Ligue 1 — Laterales
    "Achraf Hakimi":           Position.LAT,
    "Nuno Mendes":             Position.LAT,
    "Jonathan Clauss":         Position.LAT,
    "Thilo Kehrer":            Position.LAT,

    # ── Otras competiciones ─────────────────────────────────────────────────
    "Antoine Griezmann":       Position.DEL,
    "Viktor Gyökeres":         Position.DEL,
    "Marko Arnautović":        Position.DEL,
    "Endrick":                 Position.DEL,
    "Ludovic Ajorque":         Position.DEL,
    "Cucho Hernández":         Position.DEL,
    "João Félix":              Position.EXT,
    "Samuel Chukwueze":        Position.EXT,

    # ── Mundial 2026 — correcciones (API-Football asigna posición genérica) ──
    # Laterales clasificados como MC o DC
    "Wilfried Singo":          Position.LAT,
    "Ramy Bensebaini":         Position.LAT,
    "Gideon Mensah":           Position.LAT,
    "Piero Hincapié":          Position.LAT,
    "Alexander Freeman":       Position.LAT,
    "Amir Murillo":            Position.LAT,
    "Daniel Muñoz":            Position.LAT,
    "Douglas Santos":          Position.LAT,
    "Ricardo Rodríguez":       Position.LAT,
    "Jesús Gallardo":          Position.LAT,
    "Nahuel Molina":           Position.LAT,
    "Stefan Posch":            Position.LAT,
    "Ghislain Konan":          Position.LAT,
    "Quinten Timber":          Position.LAT,
    # Defensas centrales clasificados como MC
    "Marquinhos":              Position.DC,
    "Kim Min-jae":             Position.DC,
    "Issa Diop":               Position.DC,
    "Gabriel Magalhães":       Position.DC,
    "Tomás Araújo":            Position.DC,
    "Johan Vásquez":           Position.DC,
    # Delanteros clasificados como MC
    "Chris Wood":              Position.DEL,
    "Koki Ogawa":              Position.DEL,
    "Ali Alipour":             Position.DEL,
    # Extremos clasificados como MC
    "Pedro Neto":              Position.EXT,
    "Julio Enciso":            Position.EXT,
    "Junya Ito":               Position.EXT,
    # Mediapuntas clasificados como MC
    "Luka Modrić":             Position.MCO,
    "Martin Ødegaard":         Position.MCO,
    # Cristiano Ronaldo: API-Football lo asigna como "Midfielder" en Portugal/WC
    "Cristiano Ronaldo":       Position.DEL,
    "C. Ronaldo":              Position.DEL,
    # Cuti Romero: API-Football lo asigna como "Forward" en Argentina
    "Cristian Romero":         Position.DC,
    "C. Romero":               Position.DC,
}


def map_position(player_name: str, api_football_position: str) -> Position:
    """Determina la posición SFA de un jugador.

    1. Si el jugador está en KNOWN_POSITIONS, retorna esa posición.
    2. Si no, usa el mapeo base de API-Football.
    3. Si la posición de API-Football no se reconoce, retorna MC por defecto.
    """
    if player_name in KNOWN_POSITIONS:
        return KNOWN_POSITIONS[player_name]
    return BASE_POSITION_MAP.get(api_football_position, Position.MC)
